version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "yearly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
